# Generated by Django 2.2.1 on 2019-07-08 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Ciudad',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero1', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='Civil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ap_pat', models.CharField(max_length=10)),
                ('ap_mat', models.CharField(max_length=10)),
                ('fechaNacimiento', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('telefono', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('delete', models.BooleanField(default=False)),
                ('city_pk', models.ForeignKey(on_delete=models.SET(-1), to='Registro.Ciudad')),
                ('genero_pk', models.ForeignKey(on_delete=models.SET(-1), to='Registro.Genero')),
                ('relation_pk', models.ForeignKey(on_delete=models.SET(-1), to='Registro.Estado')),
            ],
            options={
                'db_table': 'Civil',
            },
        ),
    ]
